#### - Installation of Necessary Packages - 
- pandas, azure-storaage_blob, dotenv

In [1]:
%pip install pandas azure-storage_blob python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.2)
Requirement already satisfied: azure-storage_blob in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (12.28.0)
Requirement already satisfied: python-dotenv in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.1)
Requirement already satisfied: azure-core>=1.30.0 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from azure-storage_blob) (1.39.0)
Requirement already satisfied: cryptography>=2.1.4 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from azure-storage_blob) (46.0.7)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from azure-storage_blob) (4.15.0)
Requirement already satisfied: isodate>=0.6.1 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from azure-storage_blob) (0.7.2)
Requirement already satisfied: requests>=2.21.0 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from azure-core>=1.30.0->azure-storage_blob) (2.33.1)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cryptography>=2.1.4->azure-storage_blob) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cffi>=2.0.0->cryptography>=2.1.4->azure-storage_blob) (3.0)
Requirement already satisfied: six>=1.5 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage_blob) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage_blob) (3.12)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage_blob) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\okafo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage_blob) (2026.2.25)
Note: you may need to restart the kernel to use updated packages.

#### - Import Necessary Libraries

In [2]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from dotenv import load_dotenv
import os

#### - Data Extraction

In [3]:
try:
    data = pd.read_csv(r'zipco_transaction.csv')
    print("Data Extracted Successfully")
except FileNotFoundError:
    print("File not found")
except Exception as e:
    print(f"An error occurred: {e}")

Data Extracted Successfully

In [4]:
data.head()

,Date,ProductName,Quantity,UnitPrice,StoreLocation,PaymentType,PromotionApplied,Weather,Temperature,StaffPerformanceRating,...,DeliveryTime_min,OrderType,CustomerName,CustomerAddress,Customer_PhoneNumber,CustomerEmail,Staff_Name,Staff_Email,DayOfWeek,TotalSales
0,2023-01-01 00:00:00,Vanilla Cake,2,12.532304,South,Cash,True,Rainy,20.654914,Poor,...,30,In Store,William Adams,"9851 David Green\r\nTonyaburgh, VA 02853",(916)427-7276x861,lisa00@example.net,John Bridges,pdavidson@example.com,Sunday,25.064608
1,2023-01-01 01:00:00,Red Velvet Cake,1,7.083070,South,Cash,False,Rainy,23.549497,Average,...,33,In Store,Anthony Wiggins,"24682 Holly Stravenue\r\nMooreville, NH 13901",769.318.4373,michellefernandez@example.com,Sarah Bentley,ajohnson@example.net,Sunday,7.083070
2,2023-01-01 02:00:00,Chocolate Cake,5,6.736064,North,Cash,True,Rainy,NaN,Excellent,...,43,Phone Order,Ashley Duke,10184 Washington Trace Apt. 679\r\nEast Brandi...,702.520.3286,cooperwilliam@example.com,Connie Cervantes,michele29@example.net,Sunday,33.680321
3,2023-01-01 03:00:00,Carrot Cake,2,7.314823,North,Cash,False,Cloudy,20.137483,Poor,...,32,Online Order,Brandon Taylor,"87194 Jeff Rue\r\nMitchellbury, CA 50463",622-527-9530,fsilva@example.net,Jessica Stewart,xwilson@example.org,Sunday,14.629647
4,2023-01-01 04:00:00,Pizza Pepperoni,1,7.577727,East,Credit Card,True,Cloudy,23.020987,Good,...,58,In Store,Brittany Watkins,"850 Julia Groves\r\nHartview, WI 95954",759-517-8359,petersjoseph@example.net,Cheryl Carpenter,christine96@example.org,Sunday,7.577727

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    1005 non-null   str
 1   ProductName             1005 non-null   str
 2   Quantity                1005 non-null   int64
 3   UnitPrice               1005 non-null   float64
 4   StoreLocation           1005 non-null   str
 5   PaymentType             1005 non-null   str
 6   PromotionApplied        1005 non-null   bool
 7   Weather                 1005 non-null   str
 8   Temperature             904 non-null    float64
 9   StaffPerformanceRating  1005 non-null   str
 10  CustomerFeedback        905 non-null    str
 11  DeliveryTime_min        1005 non-null   int64
 12  OrderType               1005 non-null   str
 13  CustomerName            1005 non-null   str
 14  CustomerAddress         1005 non-null   str
 15  Customer_PhoneNumber    1005 non-null   str
 16  CustomerEmail           904 non-null    str
 17  Staff_Name              1005 non-null   str
 18  Staff_Email             904 non-null    str
 19  DayOfWeek               1005 non-null   str
 20  TotalSales              1005 non-null   float64
dtypes: bool(1), float64(3), int64(2), str(15)
memory usage: 158.1 KB

#### - Data Cleaning and Modelling

In [6]:
# Remove Duplicates
data.drop_duplicates(inplace=True)
print("Duplicates Removed")

Duplicates Removed

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    1000 non-null   str
 1   ProductName             1000 non-null   str
 2   Quantity                1000 non-null   int64
 3   UnitPrice               1000 non-null   float64
 4   StoreLocation           1000 non-null   str
 5   PaymentType             1000 non-null   str
 6   PromotionApplied        1000 non-null   bool
 7   Weather                 1000 non-null   str
 8   Temperature             900 non-null    float64
 9   StaffPerformanceRating  1000 non-null   str
 10  CustomerFeedback        900 non-null    str
 11  DeliveryTime_min        1000 non-null   int64
 12  OrderType               1000 non-null   str
 13  CustomerName            1000 non-null   str
 14  CustomerAddress         1000 non-null   str
 15  Customer_PhoneNumber    1000 non-null   str
 16  CustomerEmail           900 non-null    str
 17  Staff_Name              1000 non-null   str
 18  Staff_Email             900 non-null    str
 19  DayOfWeek               1000 non-null   str
 20  TotalSales              1000 non-null   float64
dtypes: bool(1), float64(3), int64(2), str(15)
memory usage: 157.4 KB

In [8]:
# Handling Missing Values (fill missing numeric values with mean or median)
numeric_columns = data.select_dtypes(include=['float64', 'int64']).columns
for col in numeric_columns:
    print(f"Handling missing values in column: {col}")
    data.fillna({col: data[col].mean()}, inplace=True)

Handling missing values in column: Quantity
Handling missing values in column: UnitPrice
Handling missing values in column: Temperature
Handling missing values in column: DeliveryTime_min
Handling missing values in column: TotalSales

In [9]:
# Handling Missing Values(fill missing string or object values with 'Unknown')
string_columns = data.select_dtypes(include=['object']).columns
for col in string_columns:
    print(f"Handling missing values in column: {col}")
    data.fillna({col: 'Unknown'}, inplace=True)

Handling missing values in column: Date
Handling missing values in column: ProductName
Handling missing values in column: StoreLocation
Handling missing values in column: PaymentType
Handling missing values in column: Weather
Handling missing values in column: StaffPerformanceRating
Handling missing values in column: CustomerFeedback
Handling missing values in column: OrderType
Handling missing values in column: CustomerName
Handling missing values in column: CustomerAddress
Handling missing values in column: Customer_PhoneNumber
Handling missing values in column: CustomerEmail
Handling missing values in column: Staff_Name
Handling missing values in column: Staff_Email
Handling missing values in column: DayOfWeek

C:\Users\okafo\AppData\Local\Temp\ipykernel_14920\2857628464.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_columns = data.select_dtypes(include=['object']).columns

In [25]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

In [10]:
data.columns

Index(['Date', 'ProductName', 'Quantity', 'UnitPrice', 'StoreLocation',
       'PaymentType', 'PromotionApplied', 'Weather', 'Temperature',
       'StaffPerformanceRating', 'CustomerFeedback', 'DeliveryTime_min',
       'OrderType', 'CustomerName', 'CustomerAddress', 'Customer_PhoneNumber',
       'CustomerEmail', 'Staff_Name', 'Staff_Email', 'DayOfWeek',
       'TotalSales'],
      dtype='str')

In [11]:
# data modelling (draw.io)

#### - Data Transformation

In [12]:
# Create the product table
products = data[['ProductName']].drop_duplicates().reset_index(drop=True)
products.index.name = 'ProductID'
products = products.reset_index()
products.to_csv('products.csv')

In [13]:
products.head(20)

   ProductID               ProductName
0          0              Vanilla Cake
1          1           Red Velvet Cake
2          2            Chocolate Cake
3          3               Carrot Cake
4          4           Pizza Pepperoni
5          5          Pizza Margherita
6          6  Pizza Beef Double decker
7          7                Cheesecake
8          8                Fruit Cake

In [14]:
# Create the Customer table
customers = data[['CustomerName', 'CustomerAddress', 'Customer_PhoneNumber', 'CustomerEmail']].drop_duplicates().reset_index(drop=True)
customers.index.name = 'CustomerID'
customers = customers.reset_index()
customers.to_csv('customers.csv', index=False)

In [15]:
customers.head()

,CustomerID,CustomerName,CustomerAddress,Customer_PhoneNumber,CustomerEmail
0,0,William Adams,"9851 David Green\r\nTonyaburgh, VA 02853",(916)427-7276x861,lisa00@example.net
1,1,Anthony Wiggins,"24682 Holly Stravenue\r\nMooreville, NH 13901",769.318.4373,michellefernandez@example.com
2,2,Ashley Duke,10184 Washington Trace Apt. 679\r\nEast Brandi...,702.520.3286,cooperwilliam@example.com
3,3,Brandon Taylor,"87194 Jeff Rue\r\nMitchellbury, CA 50463",622-527-9530,fsilva@example.net
4,4,Brittany Watkins,"850 Julia Groves\r\nHartview, WI 95954",759-517-8359,petersjoseph@example.net

In [16]:
# Create the Staff table
staff = data[['Staff_Name', 'Staff_Email']].drop_duplicates().reset_index(drop=True)
staff.index.name = 'StaffID'
staff = staff.reset_index()

In [17]:
staff.head()

   StaffID        Staff_Name              Staff_Email
0        0      John Bridges    pdavidson@example.com
1        1     Sarah Bentley     ajohnson@example.net
2        2  Connie Cervantes    michele29@example.net
3        3   Jessica Stewart      xwilson@example.org
4        4  Cheryl Carpenter  christine96@example.org

In [18]:
staff.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StaffID      1000 non-null   int64
 1   Staff_Name   1000 non-null   str
 2   Staff_Email  1000 non-null   str
dtypes: int64(1), str(2)
memory usage: 23.6 KB

In [19]:
# Create the Transaction table
transaction = data.merge(products, on=['ProductName'], how='left') \
                  .merge(customers, on=['CustomerName', 'CustomerAddress', 'Customer_PhoneNumber', 'CustomerEmail'], how='left') \
                  .merge(staff, on=['Staff_Name', 'Staff_Email'], how='left')

transaction.index.name = 'TransactionID'
transaction = transaction.reset_index() \
                          [['Date', 'TransactionID', 'ProductID', 'CustomerID', 'StaffID','Quantity', 'UnitPrice', 'StoreLocation',
                            'PaymentType', 'PromotionApplied', 'Weather', 'Temperature','StaffPerformanceRating', 
                            'CustomerFeedback', 'DeliveryTime_min','OrderType', 'DayOfWeek','TotalSales']]

In [20]:
transaction.head()

,Date,TransactionID,ProductID,CustomerID,StaffID,Quantity,UnitPrice,StoreLocation,PaymentType,PromotionApplied,Weather,Temperature,StaffPerformanceRating,CustomerFeedback,DeliveryTime_min,OrderType,DayOfWeek,TotalSales
0,2023-01-01 00:00:00,0,0,0,0,2,12.532304,South,Cash,True,Rainy,20.654914,Poor,Neutral,30,In Store,Sunday,25.064608
1,2023-01-01 01:00:00,1,1,1,1,1,7.083070,South,Cash,False,Rainy,23.549497,Average,Positive,33,In Store,Sunday,7.083070
2,2023-01-01 02:00:00,2,2,2,2,5,6.736064,North,Cash,True,Rainy,27.154342,Excellent,Unknown,43,Phone Order,Sunday,33.680321
3,2023-01-01 03:00:00,3,3,3,3,2,7.314823,North,Cash,False,Cloudy,20.137483,Poor,Positive,32,Online Order,Sunday,14.629647
4,2023-01-01 04:00:00,4,4,4,4,1,7.577727,East,Credit Card,True,Cloudy,23.020987,Good,Neutral,58,In Store,Sunday,7.577727

In [26]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    1000 non-null   datetime64[us]
 1   TransactionID           1000 non-null   int64
 2   ProductID               1000 non-null   int64
 3   CustomerID              1000 non-null   int64
 4   StaffID                 1000 non-null   int64
 5   Quantity                1000 non-null   int64
 6   UnitPrice               1000 non-null   float64
 7   StoreLocation           1000 non-null   str
 8   PaymentType             1000 non-null   str
 9   PromotionApplied        1000 non-null   bool
 10  Weather                 1000 non-null   str
 11  Temperature             1000 non-null   float64
 12  StaffPerformanceRating  1000 non-null   str
 13  CustomerFeedback        1000 non-null   str
 14  DeliveryTime_min        1000 non-null   int64
 15  OrderType               1000 non-null   str
 16  DayOfWeek               1000 non-null   str
 17  TotalSales              1000 non-null   float64
dtypes: bool(1), datetime64[us](1), float64(3), int64(6), str(7)
memory usage: 133.9 KB

In [27]:
# Save Data as CSV files
data.to_csv('cleaned_data.csv', index=False)
products.to_csv('products.csv', index=False)
customers.to_csv('customers.csv', index=False)
staff.to_csv('staff.csv', index=False)
transaction.to_csv('transaction.csv', index=False)